/**
 * Fridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Recipe { 
    id?: number;
    name?: string;
    user_id?: number;
    createdAt?: string;
    updatedAt?: string;
}

