/**
 * Fridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShoppingListProductCreate { 
    name: string;
    shopping_list_id: number;
    quantity: number;
    unit: ShoppingListProductCreate.UnitEnum;
}
export namespace ShoppingListProductCreate {
    export type UnitEnum = 'g' | 'kg' | 'ml' | 'l' | 'pcs';
    export const UnitEnum = {
        G: 'g' as UnitEnum,
        Kg: 'kg' as UnitEnum,
        Ml: 'ml' as UnitEnum,
        L: 'l' as UnitEnum,
        Pcs: 'pcs' as UnitEnum
    };
}


