/**
 * Fridge API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShoppingListProduct { 
    id?: number;
    name: string;
    shopping_list_id: number;
    quantity: number;
    unit: ShoppingListProduct.UnitEnum;
}
export namespace ShoppingListProduct {
    export type UnitEnum = 'g' | 'kg' | 'ml' | 'l' | 'pcs';
    export const UnitEnum = {
        G: 'g' as UnitEnum,
        Kg: 'kg' as UnitEnum,
        Ml: 'ml' as UnitEnum,
        L: 'l' as UnitEnum,
        Pcs: 'pcs' as UnitEnum
    };
}


