components:
  schemas:
    CreateRecipe:
      type: object
      properties:
        title:
          type: string
          description:
            type: string
        ingredients:
          type: array
          items:
            type: string
        instructions:
          type: string
        savedBy:
          type: integer
        familyId:
          type: integer
          nullable: true
        mealType:
          type: string
          enum: [ reggeli, ebéd, vacsora ]

    Recipe:
      allOf:
        - $ref: './recipe.yaml#/components/schemas/CreateRecipe'
        - type: object
          properties:
            id:
              type: integer

    UpdateRecipe:
      type: object
      properties:
        familyId:
          type: integer
          nullable: true
