export * from './family.service';
import { FamilyService } from './family.service';
export * from './recipe.service';
import { RecipeService } from './recipe.service';
export * from './shelf.service';
import { ShelfService } from './shelf.service';
export * from './shelfProduct.service';
import { ShelfProductService } from './shelfProduct.service';
export * from './shoppingList.service';
import { ShoppingListService } from './shoppingList.service';
export * from './shoppingListProducts.service';
import { ShoppingListProductsService } from './shoppingListProducts.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [FamilyService, RecipeService, ShelfService, ShelfProductService, ShoppingListService, ShoppingListProductsService, UserService];
