openapi: 3.0.0
info:
  title: Fridge Management API
  version: 1.0.0
  description: API for managing users, fridges, shelves, items, shopping lists, recipes, ingredients, and messages.
servers:
  - url: http://localhost:3001
    description: 'API server'

paths:
  /users:
    $ref: './swagger/services/user-service.yaml#/paths/~1users'
  /users/register:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1register'
  /users/login:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1login'
  /users/logout:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1logout'
  /users/user:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1user'
  /users/{userId}:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1{userId}'
  /users/email/{email}:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1email~1{email}'
  /users/google/google:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1google~1google'
  /users/google/login:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1google~1login'
  /users/google/callback:
    $ref: './swagger/services/user-service.yaml#/paths/~1users~1google~1callback'

  /fridges:
    $ref: './swagger/services/fridge-service.yaml#/paths/~1fridges'
  /fridges/{fridgeId}:
    $ref: './swagger/services/fridge-service.yaml#/paths/~1fridges~1{fridgeId}'
  /fridges/{userId}/user-fridges:
    $ref: './swagger/services/fridge-service.yaml#/paths/~1fridges~1{userId}~1user-fridges'
  /fridges/{familyId}/family-fridges:
    $ref: './swagger/services/fridge-service.yaml#/paths/~1fridges~1{familyId}~1family-fridges'

  /shelves:
    $ref: './swagger/services/shelf-service.yaml#/paths/~1shelves'
  /shelves/{shelfId}:
    $ref: './swagger/services/shelf-service.yaml#/paths/~1shelves~1{shelfId}'
  /shelves/{fridgeId}/user-shelves:
    $ref: './swagger/services/shelf-service.yaml#/paths/~1shelves~1{fridgeId}~1user-shelves'

  /products:
    $ref: './swagger/services/product-service.yaml#/paths/~1products'
  /products/{productId}:
    $ref: './swagger/services/product-service.yaml#/paths/~1products~1{productId}'
  /products/{shelfId}/shelf-products:
    $ref: './swagger/services/product-service.yaml#/paths/~1products~1{shelfId}~1shelf-products'

  /shopping-lists:
    $ref: './swagger/services/shopping-list-service.yaml#/paths/~1shopping-lists'
  /shopping-lists/{listId}:
    $ref: './swagger/services/shopping-list-service.yaml#/paths/~1shopping-lists~1{listId}'
  /shopping-lists/{listId}/items:
    $ref: './swagger/services/shopping-list-service.yaml#/paths/~1shopping-lists~1{listId}~1items'
  /shopping-lists/{listId}/items/{itemId}:
    $ref: './swagger/services/shopping-list-service.yaml#/paths/~1shopping-lists~1{listId}~1items~1{itemId}'
  /shopping-lists/{userId}/user-shopping-lists:
    $ref: './swagger/services/shopping-list-service.yaml#/paths/~1shopping-lists~1{userId}~1user-shopping-lists'

  /recipes:
    $ref: './swagger/services/recipe-service.yaml#/paths/~1recipes'
  /recipes/{recipeId}/ingredients:
    $ref: './swagger/services/recipe-service.yaml#/paths/~1recipes~1{recipeId}~1ingredients'

  /messages:
    $ref: './swagger/services/message-service.yaml#/paths/~1messages'
  /messages/chats/{chatId}/messages:
    $ref: './swagger/services/message-service.yaml#/paths/~1messages~1chats~1{chatId}~1messages'
  /messages/{messageId}:
    $ref: './swagger/services/message-service.yaml#/paths/~1messages~1{messageId}'

  /families:
    $ref: './swagger/services/family-service.yaml#/paths/~1families'
  /families/{familyId}:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1{familyId}'
  /families/{familyId}/users:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1{familyId}~1users'
  /families/{familyId}/invite:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1{familyId}~1invite'
  /families/{familyId}/leave:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1{familyId}~1leave'
  /families/{familyId}/chat:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1{familyId}~1chat'
  /families/invites/{inviteId}/accept:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1invites~1{inviteId}~1accept'
  /families/invites/{inviteId}/decline:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1invites~1{inviteId}~1decline'
  /families/invites/{userId}:
    $ref: './swagger/services/family-service.yaml#/paths/~1families~1invites~1{userId}'



components:
  schemas:
    User:
      $ref: './swagger/interfaces/user.yaml#/components/schemas/User'
    UpdateUserReq:
      $ref: './swagger/interfaces/user.yaml#/components/schemas/UpdateUserReq'
    LoginUserReq:
      $ref: './swagger/interfaces/user.yaml#/components/schemas/LoginUserReq'
    GetUserResp:
      $ref: './swagger/interfaces/user.yaml#/components/schemas/GetUserResp'
    FamilyMember:
      $ref: './swagger/interfaces/user.yaml#/components/schemas/FamilyMember'
    Fridge:
      $ref: './swagger/interfaces/fridge.yaml#/components/schemas/Fridge'
    UpdateFridgeReq:
      $ref: './swagger/interfaces/fridge.yaml#/components/schemas/UpdateFridgeReq'
    Shelf:
      $ref: './swagger/interfaces/shelf.yaml#/components/schemas/Shelf'
    UpdateShelfNameRequest:
      $ref: './swagger/interfaces/shelf.yaml#/components/schemas/UpdateShelfNameRequest'
    Product:
      $ref: './swagger/interfaces/product.yaml#/components/schemas/Product'
    ShoppingList:
      $ref: './swagger/interfaces/shopping-list.yaml#/components/schemas/ShoppingList'
    ShoppingListItem:
      $ref: './swagger/interfaces/shopping-list.yaml#/components/schemas/ShoppingListItem'
    Recipe:
      $ref: './swagger/interfaces/recipe.yaml#/components/schemas/Recipe'
    Ingredient:
      $ref: './swagger/interfaces/recipe.yaml#/components/schemas/Ingredient'
    Message:
      $ref: './swagger/interfaces/message.yaml#/components/schemas/Message'
    Chat:
      $ref: './swagger/interfaces/chat.yaml#/components/schemas/Chat'
    Family:
      $ref: './swagger/interfaces/family.yaml#/components/schemas/Family'
    Invite:
      $ref: './swagger/interfaces/family.yaml#/components/schemas/Invite'
    Invitation:
      $ref: './swagger/interfaces/invitation.yaml#/components/schemas/Invitation'
    UpdateInvitationReq:
      $ref: './swagger/interfaces/invitation.yaml#/components/schemas/UpdateInvitationReq'
    CreateInvitationReq:
      $ref: './swagger/interfaces/invitation.yaml#/components/schemas/CreateInvitationReq'
    CreateFamilyReq:
      $ref: './swagger/interfaces/family.yaml#/components/schemas/CreateFamilyReq'
  securitySchemes:
    cookieAuth:
      $ref: './swagger/services/user-service.yaml#/components/securitySchemes/cookieAuth'
